### ISSUE TITLE
AWS S3 eu-west-2 "The authorization mechanism you have provided is not supported."

### ISSUE THREAD

**Issue by dpangier** [ViViDboarder/docker-duplicity-cron#1]
The error "The authorization mechanism you have provided is not supported." occurs when used with AWS S3 buckets in eu-west-2.

The problem is boto (a python package used by duplicity). See https://lists.nongnu.org/archive/html/duplicity-talk/2015-02/msg00014.html 

I have manually updated boto in the backup container I am using, and it works fine.  Please consider using an up-to-date version of boto in your build.

**Comment by ViViDboarder** [comment]
Do you know what version of boto is required? Rather than doing the pip install, I may be able to just use a different Ubuntu base.

duplicity
Xenial: 0.7.06-2ubuntu2
Zesty: 0.7.06-2ubuntu3
Artful: 0.7.12-1ubuntu1

boto
Xenial: 2.38.0-1ubuntu1
Zesty: 2.40.0-1ubuntu1
Artful: 2.44.0-1ubuntu2

Would just bumping the base up to Artful be sufficient? If I can get a good test working with Minio it'd be much easier for me to verify. :)

**Comment by dpangier** [comment]
The version that worked for me was 2.48.0.  Documentation for the issue suggests it was fixed in 2.36.0, but 2.40.0 definitely didn't work.  I have been unable to find much detail of how this issue comes and goes, but the boto release history keeps mentioning new AWS regions.

**Comment by ViViDboarder** [comment]
Yea. Probably best to keep the pip install. Thanks.
